### ISSUE TITLE
Why do you use L_mp in part of this function, and L in another?

### ISSUE THREAD

**Issue by jeremy9959** [RabadanLab/randomly#2]
Why does line 311 reference L_mp (the eigenvalues that are consistent with the fitted MP distribution) and line 312 references L (all the eigenvalues).  Shouldn't these be the same?

https://github.com/RabadanLab/randomly/blob/7961402fbf3587d502336444a0eae4192cc076db/randomly/randomly.py#L309-L319

**Comment by luisaparicio** [comment]
Hi Jeremy,

Thanks for you interest and sorry four our delay in replaying. In line 311 we are calculating the effective gamma, i.e. gamma in terms of the first two moments of the MP eigenvalues distribution (you can see the formula in the function called _mp_parameters). In line 312 we are calculating the effective _p_ (is sort of an effective number of genes). Given that gamma is the ratio of  _n_  (number of cells) and _p_ (number of genes), the effective gamma is the ratio of _n_  and the effective _p_. That is the reason why in line 312 you simply have _n_ written as len(self.L).

**Comment by jeremy9959** [comment]
Thank you for taking the time to explain.  These are subtle points and as you can see I have read your code very carefully because I find this approach quite interesting.
